### ISSUE TITLE
can't seem to appropriately sort draw order

### ISSUE THREAD

**Issue by whoisbma** [armadillu/ofxTextureAtlas#1]
I'm unsure if this is supported, but it seems that changing the order of texture draws doesn't seem to appropriately impact the final result. How can I effectively control the draw order of textures in the atlas, in order to create the appearance of z depth, for example?

**Comment by armadillu** [comment]
The whole point of having an atlas is to draw in batch, within a single texture bind / unbind. Sadly by doing so, you have no control over the order in which tiles are drawn, as its all drawn in a single mesh / draw call in HW. You can however draw tiles at different Z levels by using the 

```
drawTextureInBatch(const std::string& filePath, const TexQuad& quad);
```

method instead of supplying an ofRectangle. By doing so, you can specify z components for each of the 3 corners of your tiles. They will all be drawn at the same time, but if you enable the depth buffer they will be properly sorted.

**Comment by armadillu** [comment]
The example may help you see how to set it up https://github.com/armadillu/ofxTextureAtlas/blob/master/exampleCustomDraw/ofApp.cpp#L81

**Comment by whoisbma** [comment]
thanks for the incredibly quick response! this is just what i needed.
